// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinkRequest) Reset() {
	*x = AddLinkRequest{}
	mi := &file_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkRequest) ProtoMessage() {}

func (x *AddLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkRequest.ProtoReflect.Descriptor instead.
func (*AddLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *AddLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinkResponse) Reset() {
	*x = AddLinkResponse{}
	mi := &file_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkResponse) ProtoMessage() {}

func (x *AddLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkResponse.ProtoReflect.Descriptor instead.
func (*AddLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *AddLinkResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type LinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkRequest) Reset() {
	*x = LinkRequest{}
	mi := &file_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRequest) ProtoMessage() {}

func (x *LinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRequest.ProtoReflect.Descriptor instead.
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *LinkRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *LinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type LinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkResponse) Reset() {
	*x = LinkResponse{}
	mi := &file_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkResponse) ProtoMessage() {}

func (x *LinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkResponse.ProtoReflect.Descriptor instead.
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *LinkResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *LinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type AddLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkRequest         `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinksRequest) Reset() {
	*x = AddLinksRequest{}
	mi := &file_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinksRequest) ProtoMessage() {}

func (x *AddLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinksRequest.ProtoReflect.Descriptor instead.
func (*AddLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *AddLinksRequest) GetLinks() []*LinkRequest {
	if x != nil {
		return x.Links
	}
	return nil
}

type AddLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkResponse        `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinksResponse) Reset() {
	*x = AddLinksResponse{}
	mi := &file_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinksResponse) ProtoMessage() {}

func (x *AddLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinksResponse.ProtoReflect.Descriptor instead.
func (*AddLinksResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *AddLinksResponse) GetLinks() []*LinkResponse {
	if x != nil {
		return x.Links
	}
	return nil
}

type RedirectLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectLinkRequest) Reset() {
	*x = RedirectLinkRequest{}
	mi := &file_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectLinkRequest) ProtoMessage() {}

func (x *RedirectLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectLinkRequest.ProtoReflect.Descriptor instead.
func (*RedirectLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *RedirectLinkRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RedirectLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectLinkResponse) Reset() {
	*x = RedirectLinkResponse{}
	mi := &file_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectLinkResponse) ProtoMessage() {}

func (x *RedirectLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectLinkResponse.ProtoReflect.Descriptor instead.
func (*RedirectLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *RedirectLinkResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_proto_shortener_proto protoreflect.FileDescriptor

const file_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortener.proto\x12\x04demo\"\"\n" +
	"\x0eAddLinkRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\")\n" +
	"\x0fAddLinkResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\tR\x06Result\"W\n" +
	"\vLinkRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"R\n" +
	"\fLinkResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\":\n" +
	"\x0fAddLinksRequest\x12'\n" +
	"\x05links\x18\x01 \x03(\v2\x11.demo.LinkRequestR\x05links\"<\n" +
	"\x10AddLinksResponse\x12(\n" +
	"\x05links\x18\x01 \x03(\v2\x12.demo.LinkResponseR\x05links\"2\n" +
	"\x13RedirectLinkRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"9\n" +
	"\x14RedirectLinkResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl2\xbc\x01\n" +
	"\x05Links\x126\n" +
	"\aAddLink\x12\x14.demo.AddLinkRequest\x1a\x15.demo.AddLinkResponse\x129\n" +
	"\bAddLinks\x12\x15.demo.AddLinksRequest\x1a\x16.demo.AddLinksResponse\x12@\n" +
	"\aGetLink\x12\x19.demo.RedirectLinkRequest\x1a\x1a.demo.RedirectLinkResponseB\fZ\n" +
	"demo/protob\x06proto3"

var (
	file_proto_shortener_proto_rawDescOnce sync.Once
	file_proto_shortener_proto_rawDescData []byte
)

func file_proto_shortener_proto_rawDescGZIP() []byte {
	file_proto_shortener_proto_rawDescOnce.Do(func() {
		file_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)))
	})
	return file_proto_shortener_proto_rawDescData
}

var file_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_shortener_proto_goTypes = []any{
	(*AddLinkRequest)(nil),       // 0: demo.AddLinkRequest
	(*AddLinkResponse)(nil),      // 1: demo.AddLinkResponse
	(*LinkRequest)(nil),          // 2: demo.LinkRequest
	(*LinkResponse)(nil),         // 3: demo.LinkResponse
	(*AddLinksRequest)(nil),      // 4: demo.AddLinksRequest
	(*AddLinksResponse)(nil),     // 5: demo.AddLinksResponse
	(*RedirectLinkRequest)(nil),  // 6: demo.RedirectLinkRequest
	(*RedirectLinkResponse)(nil), // 7: demo.RedirectLinkResponse
}
var file_proto_shortener_proto_depIdxs = []int32{
	2, // 0: demo.AddLinksRequest.links:type_name -> demo.LinkRequest
	3, // 1: demo.AddLinksResponse.links:type_name -> demo.LinkResponse
	0, // 2: demo.Links.AddLink:input_type -> demo.AddLinkRequest
	4, // 3: demo.Links.AddLinks:input_type -> demo.AddLinksRequest
	6, // 4: demo.Links.GetLink:input_type -> demo.RedirectLinkRequest
	1, // 5: demo.Links.AddLink:output_type -> demo.AddLinkResponse
	5, // 6: demo.Links.AddLinks:output_type -> demo.AddLinksResponse
	7, // 7: demo.Links.GetLink:output_type -> demo.RedirectLinkResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_shortener_proto_init() }
func file_proto_shortener_proto_init() {
	if File_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortener_proto_goTypes,
		DependencyIndexes: file_proto_shortener_proto_depIdxs,
		MessageInfos:      file_proto_shortener_proto_msgTypes,
	}.Build()
	File_proto_shortener_proto = out.File
	file_proto_shortener_proto_goTypes = nil
	file_proto_shortener_proto_depIdxs = nil
}
